services:
    _defaults:
        autoconfigure: true
        public: false

    cookiebar.anonymizeip:
        class: Oveleon\ContaoCookiebar\Command\AnonymizeIpCommand
        arguments: ['@contao.framework']
